### ISSUE TITLE
Support for "event" (PDDL+)

### ISSUE THREAD

**Issue by ZhihaoAIRobotic** [APLA-Toolbox/PythonPDDL#131]
Dose this toolbox support for PDDL+, such as "event" or "process"?

**Comment by guilyx** [comment]
Hey! Using `PDDL.jl` here, which had a discussion about PDDL+ (https://github.com/JuliaPlanners/PDDL.jl/issues/6)

This is really the backbone: https://github.com/JuliaPlanners/PDDL.jl

Long story short: not really, and can't really find the time to maintain this either sadly

**Comment by ZhihaoAIRobotic** [comment]
Thank you!!!
